### ISSUE TITLE
Error: Connection lost: The server closed the connection.

### ISSUE THREAD

**Issue by knowmerce** [jeremydaly/serverless-mysql#57]
Hi @jeremydaly ,

I use AWS Lambda, Aurora Serverless RDS.
`Error: Connection lost: The server closed the connection.` occurs sometimes.

I can't find any patterns.. 

If I don't use `await mysql.end()`, do you think will it be ok?
Please reply or any suggestion ! Thx !

**Comment by jeffledin** [comment]
I've encountered this as well. I'm unsure what is causing RDS to close the client connection; however, I am able to work around this by catching the PROTOCOL_CONNECTION_LOST error and attempting a reconnect to the database. I reconnect with the following code:
```
if (err.code === "PROTOCOL_CONNECTION_LOST") {
    console.log("Connection was dropped, reconnecting!");
    await mysql.quit();
    await mysql.connect();
}
```

After reconnecting, I retry the previously failed query. Hopefully this helps you out.

**Comment by jdchmiel** [comment]
Where are you putting that code? I am seeing the same error thrown down in libmysql2.  Are you letting it bubble up to a global error handler ?
I am not catching it in the event handlers registered when I create my pool...

**Comment by jdchmiel** [comment]
for now I added it to my formatError handler in Apollo Serverless. I will update if this is fixing for me as it seems promising.  I was never able to duplicate this issue as the pool was reconnecting when I killed the db connection from the db side as it was expected to.

**Comment by knowmerce** [comment]
@jeffledin Thanks for reply!

After I removed `await mysql.end()` errors reduced so much but still exists..
I guess It occurs sometimes when Lambda container is reused after long time passed (about over 10~20 minutes)

I'll try your suggestion.
But now, I also don't have good idea where should your code be inserted.
I use AWS Lambda + Express.

Any Idea, reply please.

**Comment by jeremydaly** [comment]
Sorry for the late reply. I've been away at re:Invent, but will investigate this more soon. Removing the `await mysql.end()` disables the connection management feature, so it's preferable *not* to do that. If is causing errors, we should be able to catch those with the library and retry.

**Comment by SebSchwartz** [comment]
I got the same error too:
```
{
    "errorType": "Error",
    "errorMessage": "Connection lost: The server closed the connection.",
    "code": "PROTOCOL_CONNECTION_LOST",
    "fatal": true,
    "stack": [
        "Error: Connection lost: The server closed the connection.",
        "    at Protocol.end (webpack:////Users//Desktop/dev/code//node_modules/mysql/lib/protocol/Protocol.js?:112:13)",
        "    at Socket.eval (webpack:////Users//Desktop/dev/code//node_modules/mysql/lib/Connection.js?:97:28)",
        "    at Socket.eval (webpack:////Users//Desktop/dev/code//node_modules/mysql/lib/Connection.js?:525:10)",
        "    at Socket.emit (events.js:215:7)",
        "    at Socket.EventEmitter.emit (domain.js:476:20)",
        "    at endReadableNT (_stream_readable.js:1183:12)",
        "    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
        "    --------------------",
        "    at Protocol._enqueue (webpack:////Users//Desktop/dev/code//node_modules/mysql/lib/protocol/Protocol.js?:144:48)",
        "    at Connection.query (webpack:////Users//Desktop/dev/code//node_modules/mysql/lib/Connection.js?:201:25)",
        "    at eval (webpack:////Users//Desktop/dev/code//node_modules/serverless-mysql/index.js?:188:25)",
        "    at new Promise (<anonymous>)",
        "    at Object.query (webpack:////Users//Desktop/dev/code//node_modules/serverless-mysql/index.js?:184:12)"
    ]
}
```

It happens when we have multiples queries done at the same time. We have a GraphQL resolver inside a lambda and some field are also resolved via this lambda (called via appsync) so we could have something like 700 queries in the same time to get this error.

**Comment by SebSchwartz** [comment]
@jeremydaly Did you get a chance to take a look into it? How can I help you with this? Do you need more log? If you need some tests I can reproduce the problem very easily (occurs multiple time a day in our env).

**Comment by SebSchwartz** [comment]
We updated to version 1.5.2 but still got the error :/

**Comment by jeremydaly** [comment]
@SebSchwartz,

How many available connections does your database have? Also, what settings are you using for the library (`connUtilization`, `usedConnsFreq`, `maxRetries`, etc.)? If you are consistently using *MORE* connections then your database has available, this library won't necessarily help.

If lots of connections are being utilized (and using more than the `connUtilization`), then the system will try and close open connections older than `zombieMinTimeout`. If you have processes that run for more than this setting (3 second default), then you could be killing open connections.

If you are optimizing the number of connections to be right on the edge of peak, then the numbers I mentioned above all need to be tweaked. Happy to look at what you've got.

Jeremy

**Comment by SebSchwartz** [comment]
@jeremydaly 
We are using Aurora Serverless as DB (MySQL). We have min 1ACUs and max 2ACUs.
We don't have settings for connUtilization, usedConnsFreq and maxRetries. Maybe this is something we could tweak?

Thanks,
Sebastien

**Comment by toonsend** [comment]
Is there a race condition here?  I was able to replicate the error 

`Connection lost: The server closed the connection`

using an express server; by killing the process via MySQL console.  The error was caught correctly by the library and the connection reset.
Could the error be caused by one thread killing a connection whilst another thread is about to use it?
**Thread 1**: Request received, Connection 1 created, Query done. Cleanup done.
Thread 1 zombieMaxTimeout  exceeded.
**Thread 2**:  Request received, Connection 2 created, Query done.
**Thread 1:** Request received, wakes up, gets its existing DB connection.
**Thread 2**: Cleans up and kills thread 1's MySQL process id.
**Thread 1**: Attempts to query on a killed MySQL connection.

**Comment by CopaCoder** [comment]
Any updates on this. It happened to me when I updated from node 8.x to 10.x

**Comment by jeremydaly** [comment]
I'm pretty sure that it's a race condition as @toonsend pointed out. I'm running some more experiments to figure out why the change with 8.x to 10.x.

**Comment by CopaCoder** [comment]
Thanks @jeremydaly appreciate your time looking forward to hearing back on this issue. AWS are forcing serverless upgrades to node 10.x starting this week so it's going to start affecting more stacks very soon.

**Comment by georgedail** [comment]
I get the same error using AWS RDS, and it only appeared after updating to node 10.x

**Comment by CopaCoder** [comment]
Any updates? The AWS deadline is looming.

https://acloud.guru/forums/aws-lambda/discussion/-LrVfksaEiXxdS1pRMKf/Node.js%208.10%20has%20reached%20its%20End%20Of%20Life

**Comment by rvgrinsven** [comment]
I'm also running into this error after  node 8.x to 12.x update. Agree with above that this will probably affect a lot of people in a bit over a week

**Comment by dominic-braeunlein** [comment]
Same error for me after updating to node 10.x

**Comment by cody-hoffman** [comment]
~Also seeing this error on node 10.x trying to connect to RDS within a VPC~

Setting our lambda's security group as an inbound source for the RDS security group resolved this issue for us.

**Comment by jeremydaly** [comment]
I've been having a hard time replicating this, but I've slotted more time tomorrow to get this resolved.

**Comment by itrendtrekhunt** [comment]
I've seen this issue come up *a lot* both before and after the upgrade from node 8, so I don't think it is node version related (although it might be).

In my case there are AWS lambda functions that are called about 2-3 times per hour. That's enough for AWS to keep them "warm", but their connections' idle time easily passes `zombieMaxTimeout` and these connections get killed by other, more frequently invoked, lambdas that use this library. On the next invocation, the rarely invoked (but still warm) lambda only realizes its connection was killed when it tries a `query()` and it gets this fabled `PROTOCOL_CONNECTION_LOST` error.

I patched `serverless-mysql` locally to retry queries on connection lost, PR here in case anyone wants it: https://github.com/jeremydaly/serverless-mysql/pull/68

**Comment by rvgrinsven** [comment]
I had also made the exact same change itrendtrekhunt made and it seemed to work fine in initial tests. I was hoping for a more elegant fix but since the 3rd of February is looming I will deploy this fix into production and call it a day :)

**Comment by jeremydaly** [comment]
Marking this as resolved with @itrendtrekhunt's patch.

**Comment by CopaCoder** [comment]
I implemented the patch but still getting the issue. see aws log

<img width="1470" alt="Screen Shot 2020-02-04 at 12 32 42 pm" src="https://user-images.githubusercontent.com/29053379/73705672-adf6b500-474a-11ea-8cad-9efe837d3580.png">

Anyone else in the same boat 🚣‍♀️ ?

**Comment by hodamirhashemi** [comment]
I still have the same issue after updating to the latest version as well. I think it's more because of my Aurora instance limited available connection.

**Comment by disbelief** [comment]
I'm also seeing this same behaviour on the latest version. I think the fix added above isn't working because the logic is added in the callback argument of `client.query`, but that callback isn't reached. Instead, the `client.query` is not catching the error so it propagates out of the library.

Stack trace:

```
Error: Connection lost: The server closed the connection. Error: Connection lost: The server closed the connection.
    at Protocol.end (/var/task/node_modules/mysql/lib/protocol/Protocol.js:112:13)
    at Socket.<anonymous> (/var/task/node_modules/mysql/lib/Connection.js:97:28)
    at Socket.<anonymous> (/var/task/node_modules/mysql/lib/Connection.js:525:10)
    at Socket.emit (events.js:203:15)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    --------------------
    at Protocol._enqueue (/var/task/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/var/task/node_modules/mysql/lib/Connection.js:201:25)
    at PromiseLibrary (/var/task/node_modules/serverless-mysql/index.js:188:25)
    at new Promise (<anonymous>)
    at Object.query (/var/task/node_modules/serverless-mysql/index.js:184:12)
```

Line 188 of serverless-mysql/index.js:
```
client.query(...args, async (err, results) => {
```

So it seems that async callback is never reached.

**Comment by tziporakk** [comment]
i got this error:
Error: Connection lost: The server closed the connection
did someone solved it?

**Comment by disbelief** [comment]
My workaround is to wrap the mysql-serverless connection, override the `query` function, catch the error and gracefully handle it:

```javascript
import mysql from 'serverless-mysql';

export default config => {
  const connection = mysql(config);

  const query = async (...args) => {
    try {
      return connection.query(...args);
    } catch (err) {
      if (
        typeof err.code !== 'undefined' &&
        (/^PROTOCOL_ENQUEUE_AFTER_/.test(err.code) ||
          err.code === 'PROTOCOL_CONNECTION_LOST' ||
          err.code === 'EPIPE')
      ) {
        connection.quit();
        return connection.query(...args);
      }
      throw err;
    }
  };

  return {
    ...connection,
    query
  };
};
```

**Comment by jeremydaly** [comment]
Hmm, shouldn't need to do that. I'll take a look.

**Comment by stevearoonie** [comment]
I've been experiencing the problem as well, in v1.5.4. My problem is that the failure occurs in beginTransaction, not query. I've worked around it by applying a similar work-around as disbelief above.

**Comment by EposCompany** [comment]
I am experiencing the same issue. has anybody been able to fix it permanently?

**Comment by sunny998877** [comment]
Server is running on port http://localhost:3000
Connected to the MySQL server.
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (/opt/bitnami/projects/chat/node_modules/mysql/lib/protocol/Protocol.js:112:13)
    at Socket.<anonymous> (/opt/bitnami/projects/chat/node_modules/mysql/lib/Connection.js:94:28)
    at Socket.<anonymous> (/opt/bitnami/projects/chat/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/opt/bitnami/projects/chat/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:314:20)
    at Protocol._delegateError (/opt/bitnami/projects/chat/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.end (/opt/bitnami/projects/chat/node_modules/mysql/lib/protocol/Protocol.js:116:8)
    at Socket.<anonymous> (/opt/bitnami/projects/chat/node_modules/mysql/lib/Connection.js:94:28)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
}

I am also facing the same issue and unable to resolve it anyone can help please!
